apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops
spec:
  selector:
    app: jenkins-server
  type: NodePort
  # Expose the Jenkins web interface on port 32000
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000